version: '2'
services:
    frodo-app:
        image: frodo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://frodo-mssql:1433;database=Frodo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://frodo-elasticsearch:9200
            - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
        ports:
            - 8080:8080
    frodo-mssql:
        extends:
            file: mssql.yml
            service: frodo-mssql
    frodo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: frodo-elasticsearch
